### ISSUE TITLE
Add representations to the different Classes

### ISSUE THREAD

**Issue by Yann-Miquel-Erdmann** [KmiQ/coinbase-advanced-python#32]
**Add representations to the different Classes**

When I print the response from a request made to coinbase, i would like to see something a bit more valuable than the default _repr_() of the class wrapping the response from the server. 

For example:
``` python
rep = client.get_product("BTC-USDC")
print(rep)
```
returns
``` console
<coinbaseadvanced.models.products.Product object at 0x7f1f8859c250>
```
seeing some data (like product_id, price ... ) instead would be great!
Here i took the get_product() as an example but the other classes have the same issue.

Thank you a lot for this library!

**Comment by KmiQ** [comment]
Thanks for the suggestion @yoyorap9. Yup, it makes sense to me. I'll try to include it as part of the next update.
