### ISSUE TITLE
Support Edit Order

### ISSUE THREAD

**Issue by jonandtice** [KmiQ/coinbase-advanced-python#50]
Coinbase API allows editing limit orders that have time-in-force of good-until-cancelled.

https://docs.cloud.coinbase.com/advanced-trade-api/reference/retailbrokerageapi_editorder

**Comment by jonandtice** [comment]
I took a shot at implementing this. See https://github.com/KmiQ/coinbase-advanced-python/pull/54

**Comment by KmiQ** [comment]
Follow Up PR here @jonandtice : https://github.com/KmiQ/coinbase-advanced-python/pull/55
